# Generated by Django 5.2.3 on 2025-06-14 16:21

from django.db import migrations, models

from recipes.utils import generate_random_short_link


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0004_favoriterecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(default=generate_random_short_link,
                                   max_length=10,
                                   unique=True,
                                   verbose_name='Короткая ссылка'),
            preserve_default=False,
        ),
    ]
