# Generated by Django 5.2.3 on 2025-06-14 16:21

import random
import string
from django.db import migrations, models

def generate_default_short_link():
    characters = string.ascii_letters + string.digits
    return ''.join(random.choice(characters) for _ in range(6))


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0004_favoriterecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(default=generate_default_short_link,
                                   max_length=10,
                                   unique=True,
                                   verbose_name='Короткая ссылка'),
            preserve_default=False,
        ),
    ]
